[project]
name = "moviedb"
version = "0.0.0"
description = "AI powered movie recommendation application"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.8",
    "django-environ>=0.12.0",
    "ipython>=9.7.0",
    "psycopg2-binary>=2.9.11",
]
